# permissions for end users to view armadacharts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: armadachart-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: armada-operator
    app.kubernetes.io/part-of: armada-operator
    app.kubernetes.io/managed-by: kustomize
  name: armadachart-viewer-role
rules:
- apiGroups:
  - armada.airshipit.org
  resources:
  - armadacharts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - armada.airshipit.org
  resources:
  - armadacharts/status
  verbs:
  - get
