apiVersion: armada.airshipit.org/v1
kind: ArmadaChart
metadata:
  labels:
    app.kubernetes.io/name: armadachart
    app.kubernetes.io/instance: armadachart-sample
    app.kubernetes.io/part-of: armada-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: armada-operator
  name: armadachart-sample
spec:
  # TODO(user): Add fields here
